
(function(){
 const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 function state(){return window.RADIUM_STATE?.()||window.__RADIUM_DATA||{};}
 async function cloudAssignments(){const tid=window.RADIUM_CLOUD?.getId?.();if(!tid||!window.RADIUM_DB)return[];const r=await window.RADIUM_DB.select('category_court_assignments',{select:'id,category_id,court_id,active,assigned_at',eq:{tournament_id:tid}});if(r.error){console.warn(r.error);return[]}return r.data||[]}
 async function renderAssignments(){const host=$('v31CategoryAssignments');if(!host)return;const d=state(), cats=(d.categories||[]).filter(c=>c.event!=='Arnis Anyo'||c.event==='Arnis Anyo');const n=Math.max(1,Number(d.setup?.courts)||1), rows=await cloudAssignments(), map=new Map(rows.map(x=>[String(x.category_id),x]));host.innerHTML=cats.map(c=>{const a=map.get(String(c.id));return `<div class="v31-court-card"><b style="min-width:0;flex:1">${esc(c.name)}</b><select data-v31-cat="${esc(c.id)}"><option value="">No court</option>${Array.from({length:n},(_,i)=>`<option value="${i+1}" ${a?.court_id?'':''}>COURT ${i+1}</option>`).join('')}</select><button class="btn small primary" data-v31-assign="${esc(c.id)}">ASSIGN</button></div>`}).join('')||'<div class="empty">Create categories first.</div>';
 host.querySelectorAll('[data-v31-cat]').forEach(sel=>{const a=map.get(sel.dataset.v31Cat);if(a){const courtRows=(d.__v31Courts||[]);const found=courtRows.find(x=>String(x.id)===String(a.court_id));sel.value=found?String(found.court_number):''}else sel.value=''});
 host.querySelectorAll('[data-v31-assign]').forEach(btn=>btn.onclick=async()=>{const cid=btn.dataset.v31Assign,sel=host.querySelector(`[data-v31-cat="${cid}"]`),num=Number(sel?.value||0);if(!num)return;try{const courts=await window.RADIUM_DB.select('courts',{select:'id,court_number',eq:{tournament_id:window.RADIUM_CLOUD.getId()}});if(courts.error)throw courts.error;const court=courts.data?.find(x=>Number(x.court_number)===num);if(!court)throw new Error('The selected court is not available.');const existing=rows.find(x=>String(x.category_id)===String(cid));let r;if(existing)r=await window.RADIUM_DB.update('category_court_assignments',{court_id:court.id,active:true,updated_at:new Date().toISOString(),assigned_by:window.RADIUM_AUTH?.user?.id||null},{id:existing.id});else r=await window.RADIUM_DB.insert('category_court_assignments',{tournament_id:window.RADIUM_CLOUD.getId(),category_id:cid,court_id:court.id,active:true,assigned_by:window.RADIUM_AUTH?.user?.id||null});if(r.error)throw r.error;await propagateCategoryCourt(cid,court.id);alert('Court assignment saved successfully.');renderAssignments()}catch(e){alert('Unable to save the court assignment. '+(e?.message||e))}});
 }
 async function propagateCategoryCourt(categoryId,courtId){const tid=window.RADIUM_CLOUD?.getId?.();if(!tid)return;const d=state();const cat=(d.categories||[]).find(c=>String(c.id)===String(categoryId));if(cat?.event==='Arnis Anyo')return;const r=await window.RADIUM_DB.select('matches',{select:'id,status',eq:{tournament_id:tid,category_id:categoryId}});if(r.error)throw r.error;for(const m of r.data||[]){if(['LIVE','COMPLETED','CANCELLED'].includes(String(m.status)))continue;const u=await window.RADIUM_DB.update('matches',{court_id:courtId,updated_at:new Date().toISOString()},{id:m.id});if(u.error)throw u.error}}
 async function loadCourtsMap(){const tid=window.RADIUM_CLOUD?.getId?.();if(!tid||!window.RADIUM_DB)return;const r=await window.RADIUM_DB.select('courts',{select:'id,court_number',eq:{tournament_id:tid}});if(!r.error)state().__v31Courts=r.data||[]}
 function globalSearch(){const input=document.querySelector('.top-search input');if(!input||input.dataset.v31Bound)return;input.dataset.v31Bound='1';let timer;const run=()=>{clearTimeout(timer);timer=setTimeout(()=>{const q=input.value.trim().toLowerCase();if(!q)return;const d=state(),role=String(window.RADIUM_AUTH?.role||'').toUpperCase(),allowPlayer=!['TABLE_OFFICIAL'].includes(role);const hits=[];for(const p of d.players||[])if(allowPlayer&&((p.name||'').toLowerCase().includes(q)||(p.number||'').toLowerCase().includes(q)))hits.push('PLAYER: '+p.name);for(const t of d.teams||[])if((t.name||'').toLowerCase().includes(q))hits.push('TEAM: '+t.name);for(const c of d.categories||[])if((c.name||'').toLowerCase().includes(q))hits.push('CATEGORY: '+c.name);const box=$('v31SearchResults')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'v31SearchResults'}));box.style.cssText='position:fixed;right:18px;top:58px;z-index:99999;background:#fff;border:1px solid #cbd5e1;border-radius:8px;padding:8px;min-width:280px;max-width:420px;box-shadow:0 12px 30px rgba(0,0,0,.18)';box.innerHTML=hits.slice(0,12).map(x=>`<div style="padding:6px 8px">${esc(x)}</div>`).join('')||'<div style="padding:8px">No matching records.</div>';},150)};input.addEventListener('input',run);input.addEventListener('keydown',e=>{if(e.key==='Escape'){input.value='';$('v31SearchResults')?.remove()}});document.addEventListener('click',e=>{if(!e.target.closest('.top-search')&&!e.target.closest('#v31SearchResults'))$('v31SearchResults')?.remove()})}
 async function teamAttendance(){const host=$('v31TeamAttendance'),tid=window.RADIUM_CLOUD?.getId?.();if(!host||!tid||!window.RADIUM_DB)return;const d=state();let teams=Array.isArray(d.teams)?d.teams:[];try{const tr=await window.RADIUM_DB.select('teams',{select:'id,name,abbreviation',eq:{tournament_id:tid}});if(!tr.error&&Array.isArray(tr.data)&&tr.data.length)teams=tr.data;}catch(e){console.warn('Team directory load failed:',e)}const r=await window.RADIUM_DB.select('team_participations',{select:'id,team_id,status,notes',eq:{tournament_id:tid}});const map=new Map((r.data||[]).map(x=>[String(x.team_id),x]));host.innerHTML=teams.map(t=>{const x=map.get(String(t.id));return `<div class="v31-court-card"><b style="flex:1">${esc(t.name)}</b><select data-att="${esc(t.id)}"><option value="EXPECTED" ${!x||x.status==='EXPECTED'?'selected':''}>EXPECTED</option><option value="PRESENT" ${x?.status==='PRESENT'?'selected':''}>PRESENT</option><option value="NO_SHOW" ${x?.status==='NO_SHOW'?'selected':''}>NO SHOW</option></select><button class="btn small primary" data-att-save="${esc(t.id)}">SAVE</button></div>`}).join('')||'<div class="empty">No teams yet.</div>';host.querySelectorAll('[data-att-save]').forEach(b=>b.onclick=async()=>{const id=b.dataset.attSave,status=host.querySelector(`[data-att="${id}"]`).value;if(status==='NO_SHOW'&&!confirm('Mark this team as NO SHOW? Active registrations for this team will also be marked NO SHOW.'))return;let x=map.get(String(id));let rr=x?await window.RADIUM_DB.update('team_participations',{status,marked_by:window.RADIUM_AUTH?.user?.id||null,marked_at:new Date().toISOString()},{id:x.id}):await window.RADIUM_DB.insert('team_participations',{tournament_id:tid,team_id:id,status,marked_by:window.RADIUM_AUTH?.user?.id||null,marked_at:new Date().toISOString()});if(rr.error)return alert('Unable to save team attendance.');if(status==='NO_SHOW'){const ur=await window.RADIUM_DB.update('category_registrations',{status:'NO_SHOW'},{tournament_id:tid,team_id:id,status:'ACTIVE'});if(ur.error)return alert('Team attendance was saved, but registrations could not be updated.');}alert('Team attendance saved.');teamAttendance();window.RADIUM_V26?.renderAccounting?.()})}
 document.addEventListener('DOMContentLoaded',()=>{globalSearch();setTimeout(async()=>{await loadCourtsMap();renderAssignments();teamAttendance()},1200)});
 document.addEventListener('radium-auth-ready',()=>setTimeout(async()=>{await loadCourtsMap();globalSearch();renderAssignments();teamAttendance()},800));
 document.addEventListener('click',e=>{if(e.target.closest('[data-page="categoriesPage"]'))setTimeout(renderAssignments,300);if(e.target.closest('[data-page="accountingPage"]'))setTimeout(teamAttendance,400)});
 window.RADIUM_V31={renderAssignments,teamAttendance,propagateCategoryCourt};
})();
